joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

servo_pan_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: servo_pan_joint
  pid: {p: 7000.0, i: 0.1, d: 300.0}

servo_tilt_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: servo_tilt_joint
  pid: {p: 7000.0, i: 0.1, d: 300.0}

ewellix_lift_top_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: ewellix_lift_top_joint
  pid: {p: 7000.0, i: 1, d: 100.0}

panda_joint_group_position_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
    - panda_finger_joint2
  panda_joint1:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_joint2:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_joint3:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_joint4:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_joint5:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_joint6:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_joint7:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_finger_joint1:
    pid: {p: 7000.0, i: 0.1, d: 30.0}
  panda_finger_joint2:
    pid: {p: 7000.0, i: 0.1, d: 30.0}

ridgeback_velocity_controller:
  type: "mecanum_drive_controller/MecanumDriveController"
  front_left_wheel_joint: "front_left_wheel"
  back_left_wheel_joint: "rear_left_wheel"
  front_right_wheel_joint: "front_right_wheel"
  back_right_wheel_joint: "rear_right_wheel"
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Override URDF look-up for wheel separation since the parent link is not the base_link.
  wheel_separation_x: 0.638
  wheel_separation_y: 0.551

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.5   # m/s^2
    y:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.5   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.0   # rad/s^2

ekf_localization:
  frequency: 50
  two_d_mode: true
  odom0: /ridgeback_velocity_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, true, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  imu0: /imu/data
  imu0_config: [false, false, false,
                false, false, false,
                false, false, false,
                false, false, true,
                true, true, false]
  imu0_differential: false
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
